version: 2.1
orbs:
  infracost: sashman/infracost@dev:1

workflows:
  build_and_test:
    jobs:
      - infracost/run-infracost-report:
          terraform_plan_file: plan.save
          terraform_file_directory: terraform/
