version: 2.1
orbs:
  infracost: sashman/infracost@0.0.6

jobs:
  read-report:
    docker:
      - image: endeveit/docker-jq
    steps:
      - attach_workspace:
          at: ~/report
      - run:
          name: Read JSON report
          command: cat ~/report/infracost.json | jq

workflows:
  build_and_test:
    jobs:
      - infracost/run-infracost-report:
          terraform_plan_file: plan.save
          terraform_file_directory: terraform/
      - infracost/save-infracost-json:
          terraform_plan_file: plan.save
          terraform_file_directory: terraform/
          infracost_report_directory: ~/report
      - read-report:
          requires:
            - infracost/save-infracost-json
